version: "3.9"

services:
  mariadb:
    image: mariadb:10.6.14
    tty: true
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./mariadb/data:/var/lib/mysql/data/
    environment:
      MYSQL_ROOT_PASSWORD: XShWJZbkijODfSsJfUHw
      MYSQL_DATABASE: wordpress
      MYSQL_USER: bengali
      MYSQL_PASSWORD: IqggGBfYniKzbuqSOdRV
    ports:
      - 3306:3306
  phpmyadmin:
    image: phpmyadmin:5.2.1
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1
    depends_on:
      - mariadb
