version: "3.9"

services:
  mariadb:
    image: mariadb:10.6.14
    tty: true
    ports:
      - 3306:3306
    volumes:
      - ./data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: XShWJZbkijODfSsJfUHw
      MYSQL_DATABASE: wordpress
      MYSQL_USER: bengali
      MYSQL_PASSWORD: IqggGBfYniKzbuqSOdRV
  wordpress:
    image: wordpress:6.2.2-php8.2-fpm-alpine
    volumes:
      - ./wordpress:/var/www/html
      - ./config/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
    ports:
      - 9000:9000
    environment:
      WORDPRESS_DB_USER: bengali
      WORDPRESS_DB_PASSWORD: IqggGBfYniKzbuqSOdRV
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_HOST: mariadb
    links:
      - mariadb
    depends_on:
      - mariadb
  nginx:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./wordpress:/var/www/html
    ports:
      - 80:80
    links:
      - wordpress
      - phpmyadmin
  phpmyadmin:
    image: phpmyadmin:5.2.1
    environment:
      PMA_HOST: mariadb
      MYSQL_ROOT_PASSWORD: XShWJZbkijODfSsJfUHw
    depends_on:
      - mariadb
