version: "3.9"

services:
  wordpress:
    image: wordpress:6.2.2-php8.2-fpm-alpine
    volumes:
      - ./wordpress:/var/www/html
      - ./config/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
    ports:
      - 9000:9000
    environment:
      WORDPRESS_DB_USER: bengali
      WORDPRESS_DB_PASSWORD: IqggGBfYniKzbuqSOdRV
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_HOST: host.docker.internal
  nginx:
    image: nginx:1.25.0-alpine
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./wordpress:/var/www/html
    ports:
      - 80:80
    links:
      - wordpress
